CC      = gcc

CFLAGS = -funroll-loops -fomit-frame-pointer -O3 -m486 -DDEBUG -w

sord.exe:  sord.o sn7649/sbpro.o tms9918/tms9918.o tms9918/drv9918.o ../z80/z80.o ../debugz80/debug_r.o ../debugz80/debug_m.o
	gcc -s -o sord.exe sord.o sn7649/sbpro.o tms9918/tms9918.o tms9918/drv9918.o ../z80/z80.o ../debugz80/debug_r.o ../debugz80/debug_m.o -lalleg

sord.o:	sord.c
	 gcc $(CFLAGS) -c sord.c

